spring.datasource.url=jdbc:mysql://172.16.0.30:3306/smds_osapi?createDatabaseIfNotExist=true&serverTimezone=UTC
spring.datasource.username=smds
spring.datasource.password=2diSenai
spring.jpa.show-sql=True
