spring.datasource.url=jdbc:mysql://172.16.0.30:3306/smds_osapi?createDatabaseIfNotExist=true&serverTimezone=UTC
spring.datasource.username=smds
spring.datasource.password=2diSenai
spring.jpa.show-sql=True
# Swagger
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha
springdoc.components.securitySchemes.ApiKeyAuth.type=apiKey
springdoc.components.securitySchemes.ApiKeyAuth.in=header
springdoc.components.securitySchemes.ApiKeyAuth.name=X-API-KEY